import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        document: "readonly",
        window: "readonly",
        globalThis: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        File: "readonly",
        Worker: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        history: "readonly",
        location: "readonly",
        navigator: "readonly",
        FormData: "readonly",
        TextDecoder: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        caches: "readonly",
        FanTeamData: "readonly",
        FanTeamState: "readonly",
        FanTeamScoring: "readonly",
        FanTeamProjection: "readonly",
        FanTeamFinance: "readonly",
        FanTeamSeasonStorage: "readonly",
        FanTeamSeasonBackup: "readonly",
        FanTeamImport: "readonly",
        FanTeamMarket: "readonly",
        FanTeamTransfers: "readonly",
        FanTeamWeek: "readonly",
        FanTeamPlanner: "readonly",
        FanTeamPlannerView: "readonly",
        FanTeamWildcard: "readonly",
        FanTeamDeadlines: "readonly",
        FanTeamHistory: "readonly",
        FanTeamEditorial: "readonly",
        FanTeamOdds: "readonly",
        PremierLeagueData: "readonly",
        PremierConsensus: "readonly",
        PremierMonteCarlo: "readonly",
        FplCopilotImport: "readonly",
        DraftFantasyImport: "readonly",
        ProbableLineupsImport: "readonly",
        PLAYERS: "writable",
        FIXTURES: "readonly",
        GW_DEADLINES: "readonly",
        CLUB_ALIASES: "readonly",
        INITIAL: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-redeclare": "error",
    },
  },
  {
    ignores: [
      "src/players-data.js",
      "src/fixtures-config.js",
      "src/fanteam-premium.css",
      "src/premier-pages.css",
      "legacy/**",
      ".local-data/**",
      "node_modules/**",
      "test-results/**",
    ],
  },
];
