const {parseBoolean:parseActualBoolean,validateKeys:validateFanTeamStatKeys,hasStats:hasFanTeamScoringStats,normalizeStats:normalizeFanTeamStats,calculatePoints:calculateFanTeamPoints}=FanTeamScoring;
const {parseActualInput,parsePriceInput,prepareActualUpdates:prepareFanTeamActualUpdates,preparePriceUpdates:prepareFanTeamPriceUpdates}=FanTeamImport;
const HISTORY_MODEL=FanTeamHistory;
state=load();if(MIGRATION_WARNINGS.length)save(state);
function applyActualUpdates(input,source=''){
  const{updates,skipped,errors,calculated,direct,mismatches}=prepareFanTeamActualUpdates(input,{players:PLAYERS,resolveClubCode,hasConfirmedSnapshot:gw=>state.history.some(h=>h.gw===gw&&Object.keys(h.forecastByPlayer||{}).length),actualFor,validActualPoints,scoring:FanTeamScoring});
  const applied=HISTORY_MODEL.applyActualUpdates({actualsByGW:state.actualsByGW,updates,importedAt:new Date().toISOString(),source});
  const nextState={...state,actualsByGW:applied.actualsByGW};
  try{save(nextState)}catch(err){throw Error('no se pudieron guardar los puntos: '+err.message)}
  state=nextState;
  MKT={gw:0,stamp:null,map:null};
  return{applied:updates.length,changed:applied.changed,removed:applied.removed,skipped,errors,calculated,direct,mismatches,gws:applied.gws};
}
function actualFor(gw,id){return HISTORY_MODEL.actualFor(state.actualsByGW,gw,id)}
function modelAccuracySummary(){return HISTORY_MODEL.modelAccuracySummary({history:state.history,actualsByGW:state.actualsByGW})}
function renderModelAccuracy(){const s=modelAccuracySummary(),set=(id,text)=>{const el=q('#'+id);if(el)el.textContent=text};set('actualGwCount',String(s.gwWithData));set('modelMae',s.mae==null?'—':s.mae.toFixed(2)+' / '+s.rmse.toFixed(2));set('captainHitRate',s.captainCount?Math.round(100*s.captainHits/s.captainCount)+'%':'—');set('transferActualGain',s.transferNet==null?'—':(s.transferNet>=0?'+':'')+s.transferNet.toFixed(2)+' pts');const select=q('#actualGW');if(select&&!select.options.length){for(let gw=1;gw<=38;gw++)select.add(new Option('GW'+gw,gw));const latest=state.history.length?state.history[state.history.length-1].gw:Math.max(1,state.gw-1);select.value=latest}const latestImport=Object.values(state.actualsByGW||{}).filter(x=>x?.importedAt).sort((a,b)=>String(b.importedAt).localeCompare(String(a.importedAt)))[0],fresh=q('#actualFreshness');if(fresh){fresh.textContent=latestImport?'Actualizado · '+new Date(latestImport.importedAt).toLocaleString('es-MX',{day:'2-digit',month:'short'}):'Sin resultados';fresh.className='pill '+(latestImport?'easy':'medium')}set('modelHistoryCount',s.evaluations.length+' pronósticos congelados');const body=q('#modelHistoryBody');if(!s.evaluations.length){body.innerHTML='<div class="historyEmpty">Confirma una jornada para empezar a medir el modelo.</div>';return}body.innerHTML=`<div class="tableWrap"><table class="table"><thead><tr><th>GW</th><th>Cobertura</th><th>Origen</th><th>Proy. / real XI+C</th><th>MAE · RMSE · sesgo</th><th>Capitán</th><th>Transferencias 3GW</th></tr></thead><tbody>${s.evaluations.map(e=>{const actualRows=Object.values(state.actualsByGW?.[e.h.gw]?.players||{}),calculatedRows=actualRows.filter(a=>a.scoringVersion==='fanteam-v1').length,cap=e.captainHit==null?'Pendiente':e.captainHit?'Acierto':'−'+e.captainRegret.toFixed(1)+' pts';const tr=e.h.transfers?.length?(e.transferNet!=null?`${e.transferNet>=0?'+':''}${e.transferNet.toFixed(2)} pts · cerrado`:e.transferObservedNet!=null?`Parcial ${e.transferObservedNet>=0?'+':''}${e.transferObservedNet.toFixed(2)} · ${e.transferObserved}/${e.transferPossible}`:'Pendiente'):'Sin cambio';return`<tr><td>GW${e.h.gw}</td><td>${e.comparisons}/${Object.keys(e.h.forecastByPlayer||{}).length}</td><td>${calculatedRows} calc. · ${actualRows.length-calculatedRows} directos</td><td>${e.h.projectedTotal==null?'—':Number(e.h.projectedTotal).toFixed(1)} / ${e.actualTotal==null?'—':e.actualTotal.toFixed(1)}</td><td>${e.mae==null?'—':e.mae.toFixed(2)+' · '+e.rmse.toFixed(2)+' · '+(e.bias>=0?'+':'')+e.bias.toFixed(2)}</td><td>${cap}</td><td>${tr}</td></tr>`}).join('')}</tbody></table></div>`}
function renderMarketTracker(){
const el=q('#marketTracker');if(!el)return;const t=marketTracker(),signed=(n,suffix='')=>(n>0?'+':'')+Number(n).toLocaleString('es-MX')+suffix,list=(rows,value,empty)=>rows.length?rows.slice(0,3).map(x=>'<small>'+esc(x.p.name)+' · '+value(x)+'</small>').join(''):'<small>'+empty+'</small>';
el.innerHTML='<div class="marketTrackerItem"><b>Subidas FanTeam</b>'+list(t.prices.risers,x=>signed(x.latest,'M'),'Sin cortes con subidas')+'</div><div class="marketTrackerItem"><b>Bajadas FanTeam</b>'+list(t.prices.fallers,x=>signed(x.latest,'M'),'Sin cortes con bajadas')+'</div><div class="marketTrackerItem"><b>Compras netas FPL</b>'+list(t.transferRisers,x=>signed(x.net),'Sin datos positivos')+'</div><div class="marketTrackerItem"><b>Ventas netas FPL</b>'+list(t.transferFallers,x=>signed(x.net),'Sin datos negativos')+'</div>'}
function renderMarket(){
renderPriceStats();renderMarketTracker();
const term=nrm(q('#marketSearch')?.value||''),pos=q('#marketPos')?.value||'',sort=q('#marketSort')?.value||'val';
const M=marketMetrics(),g=id=>M.get(id),pm=p=>priceMovementFor(p),metricSort={xg:'xg',csNext:'cleanSheetNext',points:'points',pp:'pointsPerGame',ppm:'pointsPerMillion',minutes:'historicalMinutes',matches:'matches',transfers:'netTransfers',differentialScore:'differentialScore'};
let a=PLAYERS.filter(p=>(!term||nrm(p.name+p.clubName+p.club).includes(term))&&(!pos||p.pos===pos));
a.sort((x,y)=>{if(sort==='positionalEdge')return(g(y.id).positionalEdge?.bonus??0)-(g(x.id).positionalEdge?.bonus??0)||g(y.id).h3-g(x.id).h3||x.name.localeCompare(y.name);if(sort==='selectedBy'){const xv=g(x.id).selectedBy,yv=g(y.id).selectedBy;return(xv??Infinity)-(yv??Infinity)||x.name.localeCompare(y.name)}const field=metricSort[sort];if(field){const xv=g(x.id)[field],yv=g(y.id)[field];return(yv??-Infinity)-(xv??-Infinity)||x.name.localeCompare(y.name)}return sort==='movement'?(pm(y).latest??-999)-(pm(x).latest??-999):sort==='fall'?(pm(x).latest??999)-(pm(y).latest??999):sort==='priceAsc'?x.price-y.price:sort==='priceDesc'?y.price-x.price:sort==='confidence'?y.confidence-x.confidence:sort==='name'?x.name.localeCompare(y.name):sort==='pgw'?g(y.id).pgw-g(x.id).pgw:sort==='h3'?g(y.id).h3-g(x.id).h3:sort==='h6'?g(y.id).h6-g(x.id).h6:g(y.id).val-g(x.id).val});
document.querySelectorAll('#market th[data-msort]').forEach(th=>th.classList.toggle('sortOn',th.dataset.msort===sort));
q('#marketBody').innerHTML=a.slice(0,160).map(p=>{
const m=g(p.id),move=pm(p),inS=state.squad.includes(p.id),buy=inS&&validPrice(Number(state.purchasePrices[p.id]))?Number(state.purchasePrices[p.id]):null,delta=buy==null?null:p.price-buy,fmt=(v,d=1)=>v==null?'—':Number(v).toFixed(d),pct=v=>v==null?'—':Math.round(v*100)+'%',net=m.netTransfers==null?'—':(m.netTransfers>0?'+':'')+Number(m.netTransfers).toLocaleString('es-MX'),program=m.schedule.length?m.schedule.map(s=>'<span class="diffBadge '+diffClass(s.diff)+'" title="'+esc(s.diff||'')+'">GW'+s.gw+' '+(s.home?'L':'V')+' '+esc(s.opp)+'</span>').join(''):'—',profileTags=[];
if(m.lowCeilingMidfielder?.isRisk)profileTags.push('<span class="tagOpt tagLowCeiling" title="'+esc(m.lowCeilingMidfielder.detail)+'">MID defensivo · habilitador</span>');
if(m.positionalEdge?.isEdge)profileTags.push('<span class="tagOpt '+(p.pos==='DEF'?'tagOopDef':'tagOopMid')+'" title="'+esc(m.positionalEdge.detail)+'">'+esc(m.positionalEdge.label)+'</span>');
if(m.isDifferential)profileTags.push('<span class="tagOpt tagDifferential" title="'+esc(m.differentialEdge.detail)+'">Jugador diferencial</span>');
const profileTag=profileTags.length?'<div class="playerProfileTags">'+profileTags.join('')+'</div>':'<span class="tagOpt '+m.tag.c+'" title="Clasificación del modelo">'+m.tag.t+'</span>';
return `<tr${inS?' class="rowSquad"':''}><td><span class="clubBadge">${p.club}</span> <b>${esc(p.name)}</b><br><small>${esc(p.clubName)}${inS?' · en tu plantilla':''}</small></td><td>${p.pos}</td><td class="price">${p.price.toFixed(1)}M</td><td title="Desde precio base: ${move.baseline>0?'+':''}${move.baseline.toFixed(1)}M" style="color:${move.latest>0?'var(--green)':move.latest<0?'var(--red)':'inherit'}">${move.latest==null?'—':(move.latest>0?'+':'')+move.latest.toFixed(1)+'M'}</td><td>${buy==null?'—':buy.toFixed(1)+'M'}</td><td style="color:${delta>0?'var(--green)':delta<0?'var(--red)':'inherit'}">${delta==null?'—':(delta>0?'+':'')+delta.toFixed(1)+'M'}</td><td><b>${m.pgw.toFixed(2)}</b></td><td>${m.h3.toFixed(1)}</td><td>${m.h6.toFixed(1)}</td><td><b>${m.val.toFixed(2)}</b></td><td>${fmt(m.xg,2)}</td><td>${fmt(m.xg90,2)}</td><td>${fmt(m.xgc90,2)}</td><td>${m.cleanSheets==null?'—':m.cleanSheets+(m.cleanSheetRate==null?'':' · '+pct(m.cleanSheetRate))}</td><td title="Probabilidad Poisson desde h2h + total 2.5 frescos">${pct(m.cleanSheetNext)}</td><td>${fmt(m.points,1)}${m.performanceSource?'<br><small>'+m.performanceSource+'</small>':''}</td><td>${fmt(m.pointsPerGame,2)}</td><td>${fmt(m.pointsPerMillion,2)}</td><td>${m.historicalMinutes==null?'—':Math.round(m.historicalMinutes).toLocaleString('es-MX')}</td><td>${m.matches==null?'—':m.matches}</td><td style="color:${m.netTransfers>0?'var(--green)':m.netTransfers<0?'var(--red)':'inherit'}">${net}</td><td>${m.selectedBy==null?'—':m.selectedBy.toFixed(1)+'%'}</td><td><div class="program">${program}</div></td><td><small>${p.pos} #${m.rank}</small></td><td>${p.confidence}%${p.status?'<br><small class="statChip">'+esc(p.status)+'</small>':''}</td><td>${profileTag}</td></tr>`}).join('')}
