let MKT={gw:0,stamp:null,map:null};
function marketMetrics(){
const gw=state.gw,odds=normalizedOdds(),actuals=state.actualsByGW||{},stamp=(SYNC.updatedAt||'')+'|'+SYNC.applied+'|'+ODDS_MODEL.stamp+'|'+Object.keys(actuals).length;
if(MKT.map&&MKT.gw===gw&&MKT.stamp===stamp)return MKT.map;
const map=MARKET_MODEL.metrics(PLAYERS,{gameweek:gw,actualsByGW:actuals,odds});
MKT={gw,stamp,map};return map}
let WCPLAN=null,WC_REQUEST=0,ACTIVE_WC_JOB=null;function cancelActiveWildcardWorker(){const job=ACTIVE_WC_JOB;ACTIVE_WC_JOB=null;try{job?.cancel?.()}catch{}}function clearWildcardPlan(){WC_REQUEST+=1;cancelActiveWildcardWorker();WCPLAN=null;const result=q('#wcOptResult'),apply=q('#wcApplySquad');if(result)result.innerHTML='';if(apply)apply.style.display='none'}
function recommendation(gw){return recommendationFor(state.squad,gw,state.free,gw===state.gw,buyingPower())}
function lockedCurrentRecommendation(){const d=state.decision;if(!d||(state.gw===1&&d.type==='applied'))return null;if(d.type==='applied')return{type:'transfer',double:(d.count||1)===2,out:d.out,inn:d.inn,out2:d.out2,inn2:d.inn2,gain:d.gain||0,rawGain:Number.isFinite(d.rawGain)?d.rawGain:null,reason:d.reason||'Movimiento ya aplicado en la jornada actual.',alreadyApplied:true};return{type:'save',gain:0,reason:d.reason||'Transferencia guardada en la jornada actual.',alreadyApplied:true}}
let SIX_PLAN=null;
function simulateSixWeekPlan(){return PLANNER_MODEL.simulateSixWeekPlan({gameweek:state.gw,squad:state.squad,free:state.free,bank:state.bank,lockedRecommendation:lockedCurrentRecommendation()})}
function decisionErrorMessage(code){return{'already-applied':'Este movimiento ya fue aplicado','decision-locked':'La decisión de la jornada actual ya está fijada','insufficient-free':'No hay transferencias libres suficientes','insufficient-bank':'Saldo insuficiente para este cambio'}[code]||''}
function applyDecisionToState(r,message){const result=applyCurrentDecision({state,recommendation:r});if(!result.ok){const error=decisionErrorMessage(result.code);if(error)toast(error);return result}state=result.state;if(result.code==='transfer-applied'&&state.gw===1&&state.autoDraft?.enabled!==false)state={...state,autoDraft:{...(state.autoDraft||{}),enabled:false,status:'paused',detail:'La actualización automática se pausó porque aplicaste un ajuste manual al borrador. Reactívala cuando quieras que el motor vuelva a optimizar GW1.'}};if(result.code==='transfer-applied')clearWildcardPlan();save();toast(message||(result.code==='saved'?'Transferencia guardada':r.double?'Doble cambio aplicado':'Cambio aplicado'));renderWeek();return result}
function applyPlanFirstDecision(r){if(!r)return;if(r.type==='transfer')return applyDecisionToState(r,'Primer movimiento del plan aplicado');return applyDecisionToState({...r,reason:'Decidiste acumular la transferencia gratuita siguiendo el plan de 6 jornadas.'},'Decisión del plan guardada')}
function renderSixWeekPlan(){SIX_PLAN=simulateSixWeekPlan();const p=SIX_PLAN,summary=q('#planSummary'),body=q('#sixWeekPlan'),note=q('#planNote'),button=q('#applyPlanFirst');if(!summary||!body)return;const view=PLANNER_VIEW.present({plan:p,gameweek:state.gw,decisionLocked:!!state.decision});summary.innerHTML=view.summaryHtml;body.innerHTML=view.timelineHtml;button.style.display=view.action.visible?'inline-block':'none';button.textContent=view.action.label;button.onclick=view.action.visible&&view.action.recommendation?()=>applyPlanFirstDecision(view.action.recommendation):null;note.textContent=view.note}
function applyTransferToState(r,message){if(!r||r.type!=='transfer')return;return applyDecisionToState(r,message)}
