function wildcardStatus(n,now=Date.now()){return FanTeamWildcard.status(n,{used:state['wc'+n],now,startsAt:gwDeadline(n===1?1:19),expiresAt:gwDeadline(n===1?19:38),seasonComplete:state.seasonComplete})}
function availableWildcards(now=Date.now()){return[1,2].filter(n=>wildcardStatus(n,now)==='available')}
function renderWildcards(){const risks=state.squad.map(byId).filter(p=>p.confidence<45).length,available=availableWildcards(),recommend=risks>=4&&available.length>0;const advice=q('#wcAdvice'),reason=q('#wcReason');advice.textContent=recommend?'Considerar activar Wildcard':'Conservar las Wildcards';reason.textContent=recommend?`La plantilla tiene ${risks} jugadores con riesgo elevado y la Wildcard ${available[0]} está disponible. Revisa noticias antes de reconstruir.`:available.length?`Solo hay ${risks} jugadores con riesgo elevado. Una transferencia semanal es suficiente por ahora.`:'No hay una Wildcard disponible en la ventana actual.';[['wc1',1],['wc2',2]].forEach(([k,n])=>{const status=wildcardStatus(n),card=q('#'+k+'Card'),btn=q('#'+k+'Button'),st=q('#'+k+'Status'),labels={used:'Wildcard utilizada',expired:'Wildcard caducada',future:'Aún no disponible',available:WCPLAN?'Aplicar plantilla y usar Wildcard':'Construye una plantilla para usarla'};card.className='card chip '+(status==='available'?'available':'used');st.textContent=status==='used'?'✓':status==='expired'?'×':status==='future'?'…':n;btn.textContent=labels[status];btn.disabled=status!=='available'||!WCPLAN;btn.onclick=()=>useWildcard(n)});const apply=q('#wcApplySquad');if(apply&&WCPLAN)apply.style.display=available.length===1?'':'none'}
function validWildcardPlan(){const funds=buyingPower(),ids=WCPLAN?.ids,currentCost=Array.isArray(ids)&&ids.length===15&&ids.every(id=>!!byId(id))?value(ids):Infinity,counts={};if(Array.isArray(ids))for(const id of ids){const p=byId(id);if(p)counts[p.pos]=(counts[p.pos]||0)+1}const valid=Array.isArray(ids)&&ids.length===15&&new Set(ids).size===15&&currentCost<=funds+.001&&clubValid(ids)&&Object.entries(POS_QUOTA).every(([pos,n])=>counts[pos]===n);return{valid,funds,ids,currentCost}}
function applyWildcard(n){if(wildcardStatus(n)!=='available'){toast('La Wildcard '+n+' no está disponible');return false}const plan=validWildcardPlan();if(!plan.valid){clearWildcardPlan();renderWildcards();toast('El plan quedó obsoleto; vuelve a optimizar');return false}const purchasePrices={};for(const id of plan.ids)purchasePrices[id]=byId(id).price;state={...state,['wc'+n]:true,squad:plan.ids.slice(),bank:Math.round((plan.funds-plan.currentCost)*10)/10,purchasePrices,free:0,decision:null};clearWildcardPlan();save();renderWeek();toast('Wildcard '+n+' aplicada con la plantilla completa');return true}
function useWildcard(n){if(wildcardStatus(n)!=='available'){toast('La Wildcard '+n+' no está disponible');return}if(!WCPLAN){toast('Construye primero la nueva plantilla de 15');return}if(!confirm(`¿Aplicar la nueva plantilla completa de 15 y usar la Wildcard ${n}? Las transferencias acumuladas pasarán a cero.`))return;applyWildcard(n)}
function renderWcPlan(notice='',noticeClass='easy'){
const el=q('#wcOptResult'),ap=q('#wcApplySquad');
if(!WCPLAN){el.innerHTML='<div class="callout">No se pudo construir una plantilla válida con las restricciones actuales.</div>';ap.style.display='none';return}
const gw=state.gw,xi=bestXI(WCPLAN.ids,gw);
const newOnes=WCPLAN.ids.filter(id=>!state.squad.includes(id)).length;
const groups=['GK','DEF','MID','FWD'].map(pos=>{
const ps=WCPLAN.ids.map(byId).filter(p=>p.pos===pos).sort((a,b)=>horizon6(b,gw)-horizon6(a,gw));
return '<div class="benchRow" style="margin-top:8px">'+ps.map(p=>'<div class="benchCard"><b>'+(state.squad.includes(p.id)?'':'★ ')+esc(p.name)+'</b><small>'+p.club+' · '+p.price.toFixed(1)+'M · 6GW '+horizon6(p,gw).toFixed(1)+'</small></div>').join('')+'</div>'}).join('');
el.innerHTML=(notice?'<div class="callout '+noticeClass+'" role="status" style="margin-bottom:10px">'+esc(notice)+'</div>':'')+'<div class="marketStats"><div class="card"><small>Costo</small><b>'+WCPLAN.cost.toFixed(1)+'M</b></div><div class="card"><small>Formación XI</small><b>'+xi.formation+'</b></div><div class="card"><small>Proy. XI GW'+gw+'</small><b>'+xi.pts.toFixed(1)+'</b></div><div class="card"><small>Cambios vs actual</small><b>'+newOnes+'</b></div></div>'+groups+'<div class="callout" style="margin-top:10px">★ = jugador nuevo respecto a tu plantilla actual. Al aplicar se reemplazan los 15 jugadores y se consume de forma atómica la única Wildcard disponible.</div>';
ap.style.display=availableWildcards().length===1?'':'none';renderWildcards()}
